openapi: '3.0.0'
servers:
    -   url: http://localhost:8080/
info:
    version: 1.0.0
    title: Execercise Generator API
paths:
    /exercise:
        summary: manipulate and get exercises from the BE
        get:
            tags:
                - ExerciseApi
            summary: get all exercises from BE
            operationId: getAllExercises
            responses:
                '200':
                    description: returns all exercises
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Exercise'
        post:
            tags:
                - ExerciseApi
            summary: create a new exercise
            operationId: createExercise
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Exercise'
            responses:
                '200':
                    description: new exercise was successfully created

    /exercise/{id}:
        get:
            summary: gets exercise with a specific id
            tags:
                - ExerciseApi
            operationId: getExerciseById
            parameters:
                -   in: path
                    name: id
                    schema:
                        type: string
                    required: true
                    description: ID of the exercise
            responses:
                '200':
                    description: returns exercise with a specific id
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Exercise'

    /categories:
        summary: manipulate and get categories from the BE
        get:
            tags:
                - CategoryApi
            summary: get all categories from BE
            operationId: getAllCategories
            responses:
                '200':
                    description: returns all categories
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Category'
        post:
            tags:
                - CategoryApi
            summary: create a new category
            operationId: createCategory
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Category'
            responses:
                '200':
                    description: new category was successfully created

    /categories/{id}:
        get:
            summary: gets category with a specific id
            tags:
                - CategoryApi
            operationId: getCategoryById
            parameters:
                -   in: path
                    name: id
                    schema:
                        type: string
                    required: true
                    description: ID of the category
            responses:
                '200':
                    description: returns category with a specific id
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Category'

components:
    schemas:
        LoginData:
            type: object
            description: the login data sent to the BE
            required:
                - name
                - password
            properties:
                name:
                    type: string
                password:
                    type: string

        Exercise:
            type: object
            description: the exercise object
            required:
                - title
                - text
                - categories
                - solutions
            properties:
                id:
                    type: string
                author:
                    $ref: '#/components/schemas/Author'
                title:
                    type: string
                categories:
                    type: array
                    items:
                        $ref: '#/components/schemas/Category'
                hiddenCategories:
                    type: array
                    items:
                        $ref: '#/components/schemas/Category'
                shortDescription:
                    type: string
                note:
                    type: string
                texts:
                    type: array
                    items:
                        type: string
                images:
                    type: array
                    items:
                        type: string
                solutions:
                    type: array
                    items:
                        $ref: string

        Author:
            type: object
            description: the author object
            properties:
                name:
                    type: string

        Category:
            type: object
            description: the category object
            required:
                - name
                - isHidden
            properties:
                id:
                    type: string
                name:
                    type: string
                isHidden:
                    type: boolean

        CreateExerciseDto:
            required:
                - title
                - categories
                - texts
                - solutions
            type: object
            properties:
                title:
                    type: string
                shortDescription:
                    type: string
                note:
                    type: string
                texts:
                    type: array
                    items:
                        type: string
                images:
                    type: array
                    items:
                        type: string
                solutions:
                    type: array
                    items:
                        type: string
                categories:
                    type: array
                    items:
                        $ref: '#/components/schemas/CreateCategoryDto'
                hiddenCategories:
                    type: array
                    items:
                        $ref: '#/components/schemas/CreateCategoryDto'

        CreateCategoryDto:
            type: object
            required:
                - name
                - isHidden
            properties:
                id:
                    type: string
                name:
                    type: string
                isHidden:
                    type: boolean
