openapi: 3.0.0
info:
    title: OpenAPI definition
    version: v0
servers:
    -   url: http://localhost:8080
        description: Generated server url
paths:
    /sheet:
        get:
            tags:
                - SheetApi
            operationId: getAllSheets
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Sheet"
        post:
            tags:
                - SheetApi
            operationId: createSheet
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CreateSheetDto"
                required: true
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Sheet"

    /sheet/{id}:
        get:
            tags:
                - SheetApi
            operationId: getSheetById
            parameters:
                -   name: id
                    in: path
                    required: true
                    schema:
                        type: string
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Sheet"
        delete:
            tags:
                - SheetApi
            operationId: deleteSheet
            parameters:
                -   name: id
                    in: path
                    required: true
                    schema:
                        type: string
            responses:
                "200":
                    description: OK

    /exercise:
        get:
            tags:
                - ExerciseApi
            operationId: getAllExercises
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Exercise"
        post:
            tags:
                - ExerciseApi
            operationId: createExercise
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CreateExerciseDto"
                required: true
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Exercise"

    /exercise/{id}:
        get:
            tags:
                - ExerciseApi
            operationId: getExerciseById
            parameters:
                -   name: id
                    in: path
                    required: true
                    schema:
                        type: string
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Exercise"
        delete:
            tags:
                - ExerciseApi
            operationId: deleteExercise
            parameters:
                -   name: id
                    in: path
                    required: true
                    schema:
                        type: string
            responses:
                "200":
                    description: OK

    /courses:
        get:
            tags:
                - CourseApi
            operationId: getAllCourses
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Course"
        post:
            tags:
                - CourseApi
            operationId: createCourse
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CreateCourseDto"
                required: true
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Course"

    /courses/{id}:
        get:
            tags:
                - CourseApi
            operationId: getCourseById
            parameters:
                -   name: id
                    in: path
                    required: true
                    schema:
                        type: string
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Course"
        delete:
            tags:
                - CourseApi
            operationId: deleteCourse
            parameters:
                -   name: id
                    in: path
                    required: true
                    schema:
                        type: string
            responses:
                "200":
                    description: OK

    /categories:
        get:
            tags:
                - CategoryApi
            operationId: getAllCategories
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Category"
        post:
            tags:
                - CategoryApi
            operationId: createCategory
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CreateCategoryDto"
                required: true
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Category"

    /categories/{id}:
        get:
            tags:
                - CategoryApi
            operationId: getCategoryById
            parameters:
                -   name: id
                    in: path
                    required: true
                    schema:
                        type: string
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Category"
        delete:
            tags:
                - CategoryApi
            operationId: deleteCategory
            parameters:
                -   name: id
                    in: path
                    required: true
                    schema:
                        type: string
            responses:
                "200":
                    description: OK

    /latex:
        get:
            tags:
                - TestApi
            operationId: getLatexPdf
            parameters:
                -   name: content
                    in: query
                    required: false
                    schema:
                        type: string
                        default: Hello World!
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                                    format: byte

    /latex/{exerciseId}:
        get:
            tags:
                - TestApi
            operationId: getExerciseLatex
            parameters:
                -   name: exerciseId
                    in: path
                    required: true
                    schema:
                        type: string
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                                    format: byte

    /image:
        get:
            tags:
                - TestApi
            operationId: getImage
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: string
        post:
            tags:
                - TestApi
            operationId: saveImage
            requestBody:
                content:
                    application/json:
                        schema:
                            type: string
                required: true
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: string

components:
    schemas:
        Sheet:
            type: object
            required:
                - title
                - author
                - categories
                - exercises
            properties:
                id:
                    type: string
                title:
                    type: string
                publishedAt:
                    type: string
                    format: date-time
                author:
                    $ref: "#/components/schemas/Author"
                courses:
                    type: array
                    items:
                        $ref: "#/components/schemas/Course"
                categories:
                    type: array
                    items:
                        $ref: "#/components/schemas/Category"
                exercises:
                    type: array
                    items:
                        $ref: "#/components/schemas/Exercise"

        Author:
            type: object
            required:
                - name
            properties:
                id:
                    type: string
                name:
                    type: string

        Course:
            type: object
            properties:
                id:
                    type: string
                name:
                    type: string

        Category:
            type: object
            required:
                - name
            properties:
                id:
                    type: string
                name:
                    type: string

        Exercise:
            type: object
            required:
                - title
                - categories
                - solutions
                - shortDescription
                - texts
            properties:
                id:
                    type: string
                author:
                    $ref: "#/components/schemas/Author"
                courses:
                    type: array
                    items:
                        $ref: "#/components/schemas/Course"
                categories:
                    type: array
                    items:
                        $ref: "#/components/schemas/Category"
                title:
                    type: string
                shortDescription:
                    type: string
                note:
                    type: string
                texts:
                    type: array
                    items:
                        type: string
                solutions:
                    type: array
                    items:
                        type: string
                images:
                    type: array
                    items:
                        type: string

        CreateSheetDto:
            required:
                - title
                - courses
                - categories
                - exercises
            type: object
            properties:
                title:
                    type: string
                courses:
                    type: array
                    items:
                        $ref: "#/components/schemas/CreateCourseDto"
                categories:
                    type: array
                    items:
                        $ref: "#/components/schemas/CreateCategoryDto"
                exercises:
                    type: array
                    items:
                        type: string

        CreateCourseDto:
            required:
                - name
            type: object
            properties:
                name:
                    type: string

        CreateCategoryDto:
            required:
                - name
            type: object
            properties:
                name:
                    type: string

        CreateExerciseDto:
            required:
                - title
                - courses
                - categories
                - texts
                - solutions
            type: object
            properties:
                title:
                    type: string
                courses:
                    type: array
                    items:
                        $ref: "#/components/schemas/CreateCourseDto"
                categories:
                    type: array
                    items:
                        $ref: "#/components/schemas/CreateCategoryDto"
                note:
                    type: string
                shortDescription:
                    type: string
                texts:
                    type: array
                    items:
                        type: string
                solutions:
                    type: array
                    items:
                        type: string
                images:
                    type: array
                    items:
                        type: string
