openapi: '3.0.0'
servers:
    -   url: http://localhost:8080/
info:
    version: 1.0.0
    title: Execercise Generator API
paths:
    /test:
        summary: Get test string
        get:
            tags:
                - Test
            summary: Get test string
            operationId: getTest
            responses:
                '200':
                    description: Expected response to a valid request
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: pong
    /login:
        summary: Log in with credentials
        post:
            tags:
                - Login
            summary: Log in with credentials
            operationId: logIn
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: LoginData
                description: Data to log in
            responses:
                '200':
                    description: Response if login was successful
                '400':
                    description: Response if login was not successful
components:
    schemas:
        LoginData:
            type: object
            description: Data from Login-Form
            required:
                - name
                - password
            properties:
                name:
                    type: string
                password:
                    type: string
